### ISSUE TITLE
Unhandled Promise Rejection: undefined

### ISSUE THREAD

**Issue by enableds** [luruke/barba.js#311] opened 2018-10-21 22:05 UTC
Hey there! First off, great script man, hats off it's just brilliant! I am however getting an error.

I'm using this on a mobile app, compiled using PhoneGap and Cordova ( actually, I get the same error when adding the page to the homescreen of my iOS device in WebView ) 

Animations don't fire, buttons basically work just like regular anchors. 

The code I use is this 

`$(document).ready(function(){      
    'use strict'	
    
    
    function init_template(){
         //Reinit Page Functions on Next Page           
    }
    init_template();
        
    
    var FadeTransition = Barba.BaseTransition.extend({
	  start: function() {
	    Promise
	      .all([this.newContainerLoading, this.fadeOut()])
	      .then(this.fadeIn.bind(this));
	  },
        fadeOut: function () {
            $('.page-container').addClass('disable-clicks');
            return $(this.oldContainer).promise();
        },
        fadeIn: function () {
            var _this = this;
            setTimeout(function(){
                $('.page-container:last').addClass('entering-container disable-clicks');
                $('.preloader').addClass('preloader-active');
            },100)
            setTimeout(function(){
                _this.done();
                init_template();
                $('.page-container').removeClass('entering-container disable-clicks');
                $('.preloader').removeClass('preloader-active');
            },500);
        }
    });
    Barba.Pjax.getTransition = function () {return FadeTransition;};
    Barba.Pjax.start();
});
`

I've renamed barba container and wrapper to page-wrapper and page-container, but those work flawlessly. The thing is I get a strange error. 

**
Unhandled Promise Rejection: undefined
(anonymous function)
promiseRejectionJob
**

It works great on Android Chrome Browser, iOS Chrome Browser, but when using in Webview, it's pretty much dead. 

Looking forward to your thoughts.
PS: Here's a video of the bug in action:  https://www.youtube.com/watch?v=sh3ltKacx3M I showed it browser/in webview and the error as wel. I can't get to the bottom of it.

**Comment by luruke** [comment] 2018-10-23 09:48
Hello @enableds ,
thanks for the issue.

I'll try to do some tests, is it possible that there are some CORS issue maybe?

**Comment by enableds** [comment] 2018-10-23 09:53
Heya @luruke , thanks for getting back to me. I checked it on AMPPS, MediaTemple and via the webview in Cordova, so I don't think that's the issue. It's strange because it works perfectly in browser. The only place it dies is when it's in a shell. 

It's driving me nuts! Barba is the best replacement to a tone of SPA frameworks that weigh over 1mb in scripts! 

If you wanna setup a test environment, if you're on a Mac, compile it as a cordova app an use the xcode simulator. It happens there as well. 

Cheers mate,
Looking forward to your thoughts! :)

**Comment by luruke** [comment] 2018-10-25 11:55
Hey @enableds , have you checked this? 

https://stackoverflow.com/questions/37398695/cors-cordova-issues-with-access-control-allow-origin/37398805
https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/

I'm closing the issue as the problem is not really relative to the library (I guess :D).
Cheers!

**Closed by luruke** 2018-10-25 11:55 UTC

**Comment by enableds** [comment] 2018-10-25 12:00
@luruke  It's not only happening in Cordova. It happens when you "Add to Homescreen" on iOS as well. So it's not an issue of Cordova unfortunately....

**Comment by luruke** [comment] 2018-10-25 12:17
@enableds - I just tried with a website, and after adding to homescreen (ios12) it works correctly to me.

**Comment by enableds** [comment] 2018-11-07 22:52
@luruke , I got it working perfectly on the home screen, it was not cors though. However, this has issues on iOS when compiled using Cordova/XCode. The unhandled promise rejection still appears in Cordova. 

Do you have any ideas / tips / suggestions on how to overcome this? Anything is more than welcomed!

Cheers!

**Comment by enableds** [comment] 2018-11-07 23:22
@luruke , I just tested - http://barbajs.org/demo/grid/index.html - in Cordova. Same issue occurs. The page acts like a normal HTML page. All transitions are off and then page reloads to the image. Something is wrong with the plugin itself. 

Any insights?

**Comment by enableds** [comment] 2018-11-08 10:55
@luruke , I can send you a zip file with the Cordova app using your demo to see the issue. Maybe you can diagnose it. I've added whitelists and everything needed, but still, the "Unhandled Promise Rejection: undefined" is happening. This is a barba.js plugin error... I'm lost. Been trying to figure this out for weeks now 🤕
