### ISSUE TITLE
Browsersync URL issue

### ISSUE THREAD

**Issue by nicooprat** [luruke/barba.js#116] opened 2017-02-02 10:56 UTC
First try with your library, looks great!

I'm a bit confused about how it manages URL when working with something like `http://localhost:3000/` though, using BrowserSync in my case (with Roots Sage Wordpress boilerplate). Here what's happening:

1. At first load, all URLs are correct. When clicking on a link, Barba works as expected (transitions and so on), but new link appended in the HTML now start with the ~real URL (ie. `http://myapp.dev/`). 
2. From then, clicking any link won't work as expected (full page reload).
3. With the new ~real URL, Barba works fine again, but I'm not using BrowserSync anymore, of course.

Why the ajax-appended URLs get replaced? Did I misconfigured something? Any workaround?

Thanks :)

**Comment by luruke** [comment] 2017-02-02 11:02
Hello @nicooprat , I actually have the same issue.

In order to use pushstate to manipulate the url you must respect the [Same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy), that means you can't change url to a different port.

So, in Barba.js i'm doing some check in order to verify if the url can be "followed" using pushState (https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L262)

A solution could be:
- make wordpress "output" url in the DOM with the correct port/domain.
- make some kind of proxy running on port `:3000`?

**Comment by nicooprat** [comment] 2017-02-02 11:22
* I'd have to edit each one of my template to omit the "base" URL, which is bad practice
* BrowserSync is already proxying `localhost:3000` to `myapp.dev`

In my understanding, the bug is not that Barba doesn't ajax-load pages on other domains, it's that new links appended when loading a new page are incorrect.

1. If I go from page A to page B with Barba, links are incorrect
2. Now if I force reload page B, links are correct again.

So, looks like Wordpress is echoing correct URLs, but somehow Barba replaces them before appending them in the HTML. Hope I'm clearer :)

**Comment by nicooprat** [comment] 2017-02-02 11:35
I may have misunderstood how this whole thing works... Wordpress is actually echoing `myapp.dev` links, but BrowserSync replaces each occurrence with `localhost:3000`, isn't it? In which case Barba is not in cause...

When Barba makes its Ajax call for a new page, why is BrowserSync proxy not doing its job of replacing URLs?

**Comment by nicooprat** [comment] 2017-02-02 13:41
Looks like it's the wanted behavior, but I got no chance setting the option `whitelist` like this: https://github.com/BrowserSync/browser-sync/issues/557

If I try to get content via `$.get('url')`, links aren't replaced neither, so Barba is definitely not in cause.

Looks like it's a well known issue: https://github.com/BrowserSync/browser-sync/pull/46. I tried to add this header before sending the XHR request, but had no luck neither: `req.setRequestHeader('x-requested-with', 'XMLHttpRequest')`

After spending yesterday with configuring Webpack and today BrowserSync, I'm really feeling that "javascript fatigue" :)

Hope you'll be more successful than me.

**Comment by luruke** [comment] 2017-02-02 20:11
@nicooprat Thank you for the temporary fix, maybe it can be useful for someone.
Honestly I never found it a huge deal, I find livereloading very useful mostly CSS styling.

I will update this issue in case I find other solutions.

Cheers

**Comment by nicooprat** [comment] 2017-02-03 13:23
You're welcome. But I'm not sure to understand... After a second link is clicked, I'm redirected to the non-proxied URL, then the live-reloading doesn't at all, so it'd a pretty big deal even in your case! Did I misunderstood sth?

**Comment by samburgers** [comment] 2017-05-09 00:09
Has anyone possibly found a better fix for this? The issue is killing me :)

**Comment by samburgers** [comment] 2017-05-09 00:18
update:

for anyone using wordpress... this plugin appears to solve the issue mostly by rewriting all paths to relative URLs

https://en-au.wordpress.org/plugins/relative-url/

**Closed** 2018-10-15 06:33 UTC
