### ISSUE TITLE
Background Image WordPress Header

### ISSUE THREAD

**Issue by LebCit** [luruke/barba.js#123] opened 2017-02-22 12:17 UTC
Hello @luruke 

First of all, thanks a lot for sharing this awesome plugin.
I'm testing out your plugin and it works perfectly, like it a lot 👍 
I have a WP theme and would like to implement your plugin with it.
My issue is that I have a dynamic background image header, that changes.
The background image header is set by the user as a featured image on posts and pages.
When I try your plugin, everything goes well except for the image, it doesn't change and the height is cropped to half instead of being full screen.
I'm  using jQuery to adjust the width and height of this header background image on any screen size like so
```
jQuery(document).ready(function ($) {
    // Defining a function to set size for #masthead 
    function fullscreen() {
        jQuery('#masthead').css({
            width: jQuery(window).width(),
            height: jQuery(window).height()
        });
    }

    fullscreen();

    // Run the function in case of window resize
    jQuery(window).resize(function () {
        fullscreen();
    });

});
```
My HTML structure is like the following code
```
<body>
  <div id="page">
    <nav>...</nav>
    <header id="masthead" class="intro-header">...</header> // here is the problem !
    <div id="content">...</div>
  </div>//#page
  <footer>...</footer>
</body>
```
Wherever I put `<div id="barba-wrapper">` and `<div class="barba-container">` the result is the same.
Before #page or after, before `<nav>` or after, before `<header>` or after, always same thing, everything changes except the header background image.

I'm retrieving the header background image with a function
```
function mytheme_header_style() {
    // Declare $post global if used outside of the loop.
    $post = get_post();
    // Check if post is object otherwise we're not in singular post.
    if (!is_object($post)) {
        return;
    }
    // If Object
    $backgroundImg = wp_get_attachment_image_src(get_post_thumbnail_id($post->ID), '');
    // Add inline style to the backgroung header image.
    if (has_post_thumbnail()) {
        $custom_header_style = '
            .intro-header {
                background-image: url( ' . $backgroundImg[0] . ' );
            }
        ';
    } else {
        $custom_header_style = '
            .intro-header {
                background-image: url( ' . get_template_directory_uri() . '/components/header/images/default-hero.jpg' . ' );
            }
        ';
    }
    wp_add_inline_style( 'mytheme-main-style', $custom_header_style );
}
add_action( 'wp_enqueue_scripts', 'mytheme_header_style' );
```
Hope you can help me with this.
Thanks a lot for all your efforts.

**Comment by luruke** [comment] 2017-02-22 14:30
Hello @LebCit,
can you describe a little bit better your DOM structure, is your `#masthead` inside a `barba-container`?

If it's inside a `barba-container` and it's changing for each "page" you should "re-run" your javascript code.

In the specific you can use the event `newPageReady` (http://barbajs.org/events.html)

**Comment by LebCit** [comment] 2017-02-22 19:40
Hello @luruke 

Yes my #masthead is inside `barba-container` like this
```
    <body <?php body_class(); ?>>
        <div id="page" class="site">
            <div id="barba-wrapper"> // Here is the barba wrapper
                <div class="barba-container"> // Here is the barba container
                    <a class="skip-link screen-reader-text" href="#content"><?php esc_html_e('Skip to content', 'mytheme'); ?></a>

                    <!-- Navigation -->
                    <nav id="site-navigation" class="navbar navbar-default navbar-custom navbar-fixed-top" role="navigation">
                        <?php get_template_part('components/navigation/navigation', 'top'); ?>
                    </nav>

                    <!-- Page Header -->
                    <?php // Here is the #masthead
                    if (is_404()) {
                        get_template_part('components/header/bg', '404');
                    } elseif (is_search()) {
                        get_template_part('components/header/bg', 'search');
                    } else {
                        get_template_part('components/header/bg', 'header');
                    }

                    ?>

                    <!-- Main Content -->
                    <div id="content" class="site-content container">
                        <div class="row">
```
The bg-header.php is like so
```
<?php
/**
 * This file generates the background header image with the title and the subtitle.
 * 
 * The background image is added by using inline style.
 * @see mytheme-functions.php | mytheme_header_style()
 */
?>
<header id="masthead" class="site-header intro-header" role="banner">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <header class="entry-header">
                        <?php
                        if (is_single() || is_page() || is_sticky() || is_front_page()) {
                            the_title('<h1 class="entry-title">', '</h1>');
                        } else {
                            the_title('<h1 class="entry-title"><a href="' . esc_url(get_permalink()) . '" rel="bookmark">', '</a></h1>');
                        }

                        ?>

                        <div class="strike">
                            <span>
                                <a href="#content"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                            </span>
                        </div>

                        <h2 class="subheading">
                            <?php
                            if ('post' || 'page' === get_post_type()) :
                                global $wp_query;
                                $postid = $wp_query->post->ID;
                                echo esc_html(get_post_meta($postid, '_unprefix_subtitle', true));
                                wp_reset_query();
                            endif;

                            ?>
                        </h2>
                    </header>                                             
                </div>
            </div>
        </div>
    </div>
</header>
```
The mytheme_header_style() function is described in the first comment.
So everything is returned as expected (title and subtitle), except that the image is always the same one (it's not retriving the expected image that is set as featured image), and it's not full screen.
I'm relatively new to JS :)
Thanks in advance for your help

**Comment by sndrgb** [comment] 2017-02-23 11:04
Hi @LebCit, are you sure this problem is caused by something about Barba?
When you run your fullscreen() function? 
Did you put it inside your barba lifecycle?

**Comment by luruke** [comment] 2017-03-03 13:41
@LebCit have you solved this?

Meanwhile i'll close the issue.
If you found that the issue is relative to barba.js do not hesitate to reopen it.

Cheers

**Closed by luruke** 2017-03-03 13:41 UTC
